spring.application.name=tracker
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=rutuja
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update